theme: jekyll-theme-cayman
title: Computer Science
description: Collection of **Computer Science** (incl. Software Enginerring) articles, notes and cheet sheets. Designe for educational purposes and builded with GitHub PAges technology. To read more about use of this information, please reffer to the [LICENSE](LICENSE).

